const loginBox=document.getElementById('loginBox'), adminBox=document.getElementById('adminBox'), pass=document.getElementById('password'), form=document.getElementById('gameForm'), list=document.getElementById('list'), folderInput=document.getElementById('folder'), linkInput=document.getElementById('link'), previewLink=document.getElementById('previewLink'), previewImage=document.getElementById('previewImage'), adminSearch=document.getElementById('adminSearch');
let games=[];
function safeText(t=''){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function val(id){return document.getElementById(id).value.trim()}
function statusText(s){return window.APP_CONFIG.STATUS_LABELS[s]||s||'เปิดเล่น'}
function buildLink(folder){folder=(folder||'').replace(/^games\//,'').replace(/\/index\.html$/,'').replace(/^\/+|\/+$/g,''); return folder?`games/${folder}/index.html`:''}
function coverPath(folder){folder=(folder||'').replace(/^games\//,'').replace(/\/index\.html$/,'').replace(/^\/+|\/+$/g,''); return folder?`games/${folder}/cover.png`:''}
function updateLinkPreview(){const l=buildLink(folderInput.value); const img=coverPath(folderInput.value); linkInput.value=l; previewLink.textContent=l||'games/ชื่อโฟลเดอร์/index.html'; if(previewImage) previewImage.textContent=img||'games/ชื่อโฟลเดอร์/cover.png'}
folderInput?.addEventListener('input',updateLinkPreview);
function login(){if(pass.value===window.APP_CONFIG.ADMIN_PASSWORD){localStorage.setItem('admin_ok','1'); showAdmin()}else alert('รหัสไม่ถูกต้อง')}
function logout(){localStorage.removeItem('admin_ok'); location.reload()}
pass?.addEventListener('keydown',e=>{if(e.key==='Enter')login()}); if(localStorage.getItem('admin_ok')==='1')showAdmin();
async function showAdmin(){loginBox.classList.add('hidden'); adminBox.classList.remove('hidden'); await loadGames()}
async function loadGames(){list.innerHTML='<p class="empty">กำลังโหลดข้อมูล...</p>'; try{await window.firebaseReady; const snap=await window.gamesRef.orderBy('createdAt','desc').get(); games=snap.docs.map(d=>({id:d.id,...d.data(), folder:d.data().folder||d.data().gameFolder||'', link:d.data().link||d.data().gameUrl||buildLink(d.data().folder||d.data().gameFolder||'')}));}catch(e){console.error(e); games=[]; list.innerHTML='<p class="empty">โหลดข้อมูลไม่สำเร็จ กรุณาตรวจสอบ Firestore Rules</p>'; return} renderStats(); renderList()}
function renderStats(){document.getElementById('totalGames').textContent=games.length; document.getElementById('openGames').textContent=games.filter(g=>g.status==='open').length; document.getElementById('soonGames').textContent=games.filter(g=>g.status==='soon').length;}
function renderList(){const key=(adminSearch?.value||'').toLowerCase(); const data=games.filter(g=>(g.title||'').toLowerCase().includes(key)||(g.category||'').toLowerCase().includes(key)||(g.folder||'').toLowerCase().includes(key)); if(!data.length){list.innerHTML='<p class="empty">ยังไม่มีเกม</p>'; return} list.innerHTML=data.map(g=>`<div class="item"><img src="${safeText(g.image||coverPath(g.folder))}" onerror="this.style.display='none'"><div><b>${safeText(g.title||'ไม่มีชื่อเกม')}</b><small>${safeText(g.category||'ไม่ระบุ')} | ${safeText(statusText(g.status))}</small><small>📁 ${safeText(g.folder||'-')} → ${safeText(g.link||buildLink(g.folder))}</small></div><div class="btns"><button class="mini view" onclick="window.open('${safeText(g.link||buildLink(g.folder))}','_blank')">ดู</button><button class="mini copy" onclick="copyLink('${safeText(g.link||buildLink(g.folder))}')">คัดลอก</button><button class="mini edit" onclick='editGame(${JSON.stringify(g).replaceAll("'","&apos;")})'>แก้ไข</button><button class="mini del" onclick="deleteGame('${g.id}')">ลบ</button></div></div>`).join('')}
adminSearch?.addEventListener('input',renderList);
form.addEventListener('submit',async e=>{e.preventDefault(); const id=val('id'); const folder=val('folder'); const link=buildLink(folder); if(!val('title'))return alert('กรุณากรอกชื่อเกม'); if(!folder)return alert('กรุณากรอกชื่อโฟลเดอร์เกม'); const now=firebase.firestore.FieldValue.serverTimestamp(); const data={title:val('title'),description:val('description'),category:val('category'),image:val('image')||coverPath(folder),folder,link,gameUrl:link,status:val('status')||'open',updatedAt:now}; try{await window.firebaseReady; if(id) await window.gamesRef.doc(id).update(data); else await window.gamesRef.add({...data,createdAt:now}); alert('บันทึกสำเร็จ'); resetForm(); await loadGames()}catch(err){console.error(err); alert('บันทึกไม่สำเร็จ กรุณาตรวจสอบ Firestore Rules')}});
function editGame(g){document.getElementById('id').value=g.id||''; document.getElementById('title').value=g.title||''; document.getElementById('description').value=g.description||''; document.getElementById('category').value=g.category||'อื่น ๆ'; document.getElementById('image').value=g.image||''; document.getElementById('folder').value=g.folder||''; document.getElementById('status').value=g.status||'open'; updateLinkPreview(); scrollTo({top:0,behavior:'smooth'})}
async function deleteGame(id){if(!confirm('ลบเกมนี้ใช่ไหม?'))return; try{await window.firebaseReady; await window.gamesRef.doc(id).delete(); await loadGames()}catch(e){console.error(e); alert('ลบไม่สำเร็จ')}}
function resetForm(){form.reset(); document.getElementById('id').value=''; updateLinkPreview()}
function copyLink(link){const full=new URL(link,location.href).href; navigator.clipboard?.writeText(full); alert('คัดลอกลิงก์แล้ว\n'+full)}
window.login=login; window.logout=logout; window.editGame=editGame; window.deleteGame=deleteGame; window.resetForm=resetForm; window.copyLink=copyLink;
